name: book_bridge_app
description: "An online classified marketplace that enables students to discover, buy, and sell used physical books within their locality."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.1
  google_sign_in: ^6.1.5
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  mockito: ^5.6.1
  flutter_launcher_icons: ^0.13.1

  cloud_firestore_platform_interface: any
  firebase_auth_platform_interface: any
  google_sign_in_platform_interface: any

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "App_Icon.png"
  min_sdk_android: 21 # android version
